name: merge-workflow-master-changes-to-all-branch

on:
  push:
    paths:
      - '.github/**'
    branches:
      - master

jobs:
  merge-workflow-master-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set git user config
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global advice.detachedHead false

      - name: Check if .github folder was modified
        id: check_changes
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^\.github/')" ]; then
            echo "MODIFIED=true" >> $GITHUB_ENV
          else
            echo "MODIFIED=false" >> $GITHUB_ENV
          fi

      - name: Merge changes into other branches
        if: env.MODIFIED == 'true'
        run: |
          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}

          # Define strings to exclude
          EXCLUDED_STRINGS="$DEFAULT_BRANCH|origin/gh-pages"
          
          # Loop through your branches and merge changes
          for branch in $(git branch -r | grep -v -E "$EXCLUDED_STRINGS" | awk '{gsub(/^[^\/]+\//,"",$1); print $1}'); do
            git checkout $branch
            git checkout $DEFAULT_BRANCH -- .github/
            git add .github/
            git commit -m "Sync .github folder from $DEFAULT_BRANCH"
            git push origin $branch
          done
