name: update-city-list-json

on:
  schedule:
    - cron: '0 0 * * *'  # Run once daily at midnight
  workflow_dispatch:
  
jobs:
  updating-city-list-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and decompress gzipped file
      run: |
        wget -q https://bulk.openweathermap.org/sample/city.list.min.json.gz
        gunzip city.list.min.json.gz

    - name: Rename and Move JSON file to public/assets Directory
      run: |
        mv city.list.min.json city_list.json
        mv city_list.json public/assets/

    - name: Set Git user config
      run: |
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER_NAME }}
        
    - name: Commit and push changes
      run: |
        git add public/assets/city_list.json
        git commit --allow-empty -m "Update city_list.json"
        git push origin master

    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: |
        npm i --slient && npm run predeploy
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        npm run deploy
        
