name: update-city-list-json

on:
  schedule:
    - cron: '0 */6 * * *'  # Run once daily at midnight
  workflow_dispatch:
  
jobs:
  updating-city-list-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and decompress gzipped file
      shell: bash
      env:
        URL: ${{ secrets.CITY_LIST_JSON_URL }}
      run: |
        if wget -q ${URL} then;
          gunzip city.list.min.json.gz
        else
          echo "ERROR: Cannot download city JSON file." && exit 1
        fi

    - name: Rename and Move JSON file to public/assets Directory
      run: |
        mv city.list.min.json public/assets/city_list.json
        
    - name: Set Git user config
      run: |
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER_NAME }}
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add public/assets/city_list.json
        if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Your commit message"
            git push origin master
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            echo "COMMIT=true" >> $GITHUB_ENV
        else
            echo "No changes to commit."
        fi
    - name: Deploy
      if: ${{ env.COMMIT == 'true' }}
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: |
        npm i --slient --loglevel error && npm run predeploy
        npm run deploy
        
