name: update-city-list-json

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force Deploy'
        type: boolean
        required: false
  push:
    branches:
      - master
  
jobs:
  updating-city-list-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set git user config
      run: |
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER_NAME }}

    - name: Download and decompress gzipped file
      shell: bash
      env:
        URL: ${{ secrets.CITY_LIST_JSON_URL }}
      run: |
        wget -q ${URL}
        if [  $? -eq 0 ]; then
          echo "Download Successful"
          gunzip city.list.min.json.gz
        else
          echo "ERROR: Cannot download city JSON file." && exit 1
        fi

    - name: Rename and Move JSON file to public/assets Directory
      run: |
        mv city.list.min.json src/assets/city_list.json
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add src/assets/city_list.json
        git remote set-url origin https://git:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Your commit message"
            git push origin master
            echo "COMMIT=true" >> $GITHUB_ENV
        else
            echo "No changes to commit."
        fi
        
    - name: Deploy
      if: ${{ github.event.inputs.force_deploy == 'true' || env.COMMIT == 'true' }}
      env:
        REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: |
        npm i --slient --loglevel error && npm run predeploy
        npm run deploy
        
